### ISSUE TITLE
Introduce undo.step config option

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-undo#11]
At least two packages need it: typing and delete.

The default value should be defined in this package. Of course, other packages which want to use it cannot assume that it's set, unless they explicitly require the Undo feature.

The above makes it a bit messy, because both typing and delete use option which may or may not be defined. So in some way they need to define the default value anyway, and we thought that since this value goes straight to the `ChangeBuffer` it could be defined there (as a default param).

This makes me think that perhaps `ChangeBuffer` could be moved to this package. It's mostly related to undo.

**Comment by pjasiun** [comment]
> At least two packages need it: typing and delete.

I have stronger and stronger feeling that typing, delete and enter are in fact one "text" feature. This limit is only about this features, it is not about undo, in will not be useful in any other plugin.

Also these plugins does not work separately: if you disable delete feature, you can still delete, because typing will handle it by mutations. I see no profit in keeping these features separated, but we have problems with it. 

Both `ChangeBuffer` and the default undo step for text are the `text` feature things.

**Comment by Reinmar** [comment]
Makes a lot of sense. Although, I'd like to see some solution for the issue with typing feature handling also backspace (for text). I agree though that merging them into one package may make sense. So we'd have `ckeditor5-text` (or `ckeditor5-editing` or something better) with:

* typing,
* enter,
* delete,
* `ChangeBuffer`,
* all the commands.

**Comment by pjasiun** [comment]
If we call it ` ckeditor5-editing` then people start asking what all other repos are doing ;)

**Comment by Reinmar** [comment]
OTOH, it doesn't clearly explain how and where the default value of `editing.undoStep` (much better than `text.undoStep` in fact) would be defined :D. There are 3 options:

* in some base feature that the other ones would require (but it still may not be loaded if someone used only the command),
* in both usage places: typing and delete,
* in `ChangeBuffer` (so without a default for the config option itself).

**Comment by Reinmar** [comment]
As for the name – we also realised that if we call the repo 'text', then enter options will look weird: `text.shiftEnterSth`. 'editing' looks much better, but I agree that it's not perfect.

**Comment by fredck** [comment]
I'm still for `typing`, which basically groups the main actions one takes to change the content by using the keyboard (or keyboard-like input methods). It should be fine.

**Comment by Reinmar** [comment]
Makes sense. So we're talking about merging other repositories into this, we'll have `typing.undoStep` and `ChangeBuffer` shared by these classes. We can also have `typing.Typing` feature which would require `typing.Input` and `typing.Delete`, so you can have them separately or all at the same time if needed (99.9999% cases :D).

One thing that I'm unsure is whether I'd like to see the enter feature merged as well. If we think about typing as about textarea's capabilities, then perhaps yes. But while typing and delete are obligatory, enter is a bit optional so makes for a new. It also doesn't share any code with the two other features.

I talked with @fredck about the enter and he agrees.

**Comment by fredck** [comment]
I agree. From outside, typing and delete seem to be two parts of the same essential feature which will be in 100% of the cases. Enter is in fact a different story.

**Comment by pjasiun** [comment]
> From outside, typing and delete seem to be two parts of the same essential feature which will be in 100% of the cases.

From inside too ;)

> Enter is in fact a different story.

I also agree. You may want to have an input-like editor, which will have typing feature, but no enter.

**Comment by Reinmar** [comment]
Will be fixed by https://github.com/ckeditor/ckeditor5-typing/issues/17.
