### ISSUE TITLE
One undo step reverts more than one change

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-undo#43]
![undo](https://cloud.githubusercontent.com/assets/1057056/18992402/5fc118c0-871e-11e6-8adb-e81726193253.gif)

**Comment by Reinmar** [comment]
DUP of https://github.com/ckeditor/ckeditor5-typing/issues/21 and https://github.com/ckeditor/ckeditor5-typing/issues/20.
