### ISSUE TITLE
Error: move-operation-position-invalid with image upload

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-undo#62]
#### Steps to reproduce:
1. Start manual test: http://localhost:8125/ckeditor5-upload/tests/manual/imageupload.html.
2. Insert image to upload.
3. Select the image and delete it.
4. Use `Undo`.

#### Result:
`CKEditorError: move-operation-position-invalid: Source position or target position is invalid.`

![output](https://cloud.githubusercontent.com/assets/2396463/25987516/a9e0e012-36f4-11e7-9fd6-4f034eb43d4d.gif)

**Comment by scofalik** [comment]
This exact error does not occur anymore but we have other error with this scenario now. See https://github.com/ckeditor/ckeditor5-undo/issues/65#issuecomment-313619534

**Comment by Reinmar** [comment]
Is a different case and it's really hard to reproduce (I needed a couple of tries to figure out the exact steps), so let's close this ticket as the bug reported here was closed. For the other one we have the umbrella ticket (and a lot more time to fix it ;)).
