### ISSUE TITLE
Let features know about undo batch

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-undo#97]
So I have an issue with undoing automatic text transformations. Scenario:
- user types "woot"
- feature replaces "woot" to „woot” (using a new batch)
- users decides to undo change (CTRL-Z) to "woot"
Now the feature does not know if that `"data:change"` event is for undoing batch. I can listen to undo command execution and filter out those batches but it looks like we could add another type of batch?

This is rather open discussion as I only know about: `default` and `transparent` type of batches ATM.

**Comment by jodator** [comment]
So after F2F talks with @scofalik we came to a conclusion that adding a batch type "undo" makes sense:
- there's an actual need of other features to know about that change is coming from "undo" not user interaction
- another solution for this problem looks less clean (ie checking if batch is in undo stack)
- the redo should also have "undo" type - as in such scenario:
    1. user types "foo bar"
    2. text transformation changes to `„foo bar”`
    3. user undo (1): text becomes `"foo bar"` again
    4. user undo (2): part of text (depending on buffer) is removed: `"foo`
    5. user redo (1): the text should be `"foo bar"` (and no automatic transformation to be applied)
    6. user redo (2): the transformation i re-applied: `„foo bar”`

At the moment I see that `undo` type makes sense as
- features might introduce other types of batch.
- the `undo` batch will be present only with `Undo` plugin enabled
- the batch type should be documented in feature description

//cc @pjasiun

**Comment by pjasiun** [comment]
I'm fine with marking "undo" and "redo" batches as "undo" with a special flag.

**Comment by jodator** [comment]
> batches as "undo" with a special flag.

@pjasiun: To be precise: `batch.specialFlag = true` or `batch.type = 'undo'` - the latter (`batch.type=undo`) was proposed here.

**Comment by pjasiun** [comment]
After F2F talk we agreed that we can try to mark these baches as transparent.

**Comment by jodator** [comment]
After another F2F talk with @pjasiun & @scofalik we agreed on checking first if the undo feature shouldn't use transparent batches in the first place (instead of currently default).
